/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SyncRoleRouteImport } from './routes/sync-role'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminCurriculumRouteImport } from './routes/admin.curriculum'
import { Route as AdminGamificationRouteImport } from './routes/admin.gamification'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SchoolIndexRouteImport } from './routes/school.index'
import { Route as SchoolClassesRouteImport } from './routes/school.classes'
import { Route as SchoolReadinessRouteImport } from './routes/school.readiness'
import { Route as SchoolReportsRouteImport } from './routes/school.reports'
import { Route as SchoolStudentsRouteImport } from './routes/school.students'
import { Route as SchoolTeachersRouteImport } from './routes/school.teachers'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentClubsRouteImport } from './routes/student.clubs'
import { Route as StudentCompeteRouteImport } from './routes/student.compete'
import { Route as StudentLabRouteImport } from './routes/student.lab'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentPortfolioRouteImport } from './routes/student.portfolio'
import { Route as StudentPracticeRouteImport } from './routes/student.practice'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherReviewsRouteImport } from './routes/teacher.reviews'
import { Route as StudentBuildIndexRouteImport } from './routes/student.build.index'
import { Route as StudentBuildProjectIdRouteImport } from './routes/student.build.$projectId'
import { Route as StudentLearnIndexRouteImport } from './routes/student.learn.index'
import { Route as StudentLearnPathIdRouteImport } from './routes/student.learn.$pathId'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher.classes.index'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes.$classId'
import { Route as TeacherStudentsIndexRouteImport } from './routes/teacher.students.index'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoleRoute = SyncRoleRouteImport.update({
  id: '/sync-role',
  path: '/sync-role',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamificationRoute = AdminGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolClassesRoute = SchoolClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolReadinessRoute = SchoolReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolReportsRoute = SchoolReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolStudentsRoute = SchoolStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolTeachersRoute = SchoolTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => SchoolRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClubsRoute = StudentClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCompeteRoute = StudentCompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLabRoute = StudentLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPortfolioRoute = StudentPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReviewsRoute = TeacherReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentBuildIndexRoute = StudentBuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBuildProjectIdRoute = StudentBuildProjectIdRouteImport.update({
  id: '/build/$projectId',
  path: '/build/$projectId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnIndexRoute = StudentLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnPathIdRoute = StudentLearnPathIdRouteImport.update({
  id: '/learn/$pathId',
  path: '/learn/$pathId',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsIndexRoute = TeacherStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/school': typeof SchoolRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/sync-role': typeof SyncRoleRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/school/classes': typeof SchoolClassesRoute
  '/school/readiness': typeof SchoolReadinessRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/students': typeof SchoolStudentsRoute
  '/school/teachers': typeof SchoolTeachersRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/clubs': typeof StudentClubsRoute
  '/student/compete': typeof StudentCompeteRoute
  '/student/lab': typeof StudentLabRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reviews': typeof TeacherReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/build/$projectId': typeof StudentBuildProjectIdRoute
  '/student/learn/$pathId': typeof StudentLearnPathIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/build/': typeof StudentBuildIndexRoute
  '/student/learn/': typeof StudentLearnIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sync-role': typeof SyncRoleRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/school/classes': typeof SchoolClassesRoute
  '/school/readiness': typeof SchoolReadinessRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/students': typeof SchoolStudentsRoute
  '/school/teachers': typeof SchoolTeachersRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/clubs': typeof StudentClubsRoute
  '/student/compete': typeof StudentCompeteRoute
  '/student/lab': typeof StudentLabRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reviews': typeof TeacherReviewsRoute
  '/admin': typeof AdminIndexRoute
  '/school': typeof SchoolIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/build/$projectId': typeof StudentBuildProjectIdRoute
  '/student/learn/$pathId': typeof StudentLearnPathIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/build': typeof StudentBuildIndexRoute
  '/student/learn': typeof StudentLearnIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/students': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/school': typeof SchoolRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/sync-role': typeof SyncRoleRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/gamification': typeof AdminGamificationRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/school/classes': typeof SchoolClassesRoute
  '/school/readiness': typeof SchoolReadinessRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/students': typeof SchoolStudentsRoute
  '/school/teachers': typeof SchoolTeachersRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/clubs': typeof StudentClubsRoute
  '/student/compete': typeof StudentCompeteRoute
  '/student/lab': typeof StudentLabRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reviews': typeof TeacherReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/build/$projectId': typeof StudentBuildProjectIdRoute
  '/student/learn/$pathId': typeof StudentLearnPathIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/build/': typeof StudentBuildIndexRoute
  '/student/learn/': typeof StudentLearnIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/school'
    | '/student'
    | '/sync-role'
    | '/teacher'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/competitions'
    | '/admin/curriculum'
    | '/admin/gamification'
    | '/admin/moderation'
    | '/admin/questions'
    | '/admin/schools'
    | '/admin/users'
    | '/school/classes'
    | '/school/readiness'
    | '/school/reports'
    | '/school/students'
    | '/school/teachers'
    | '/student/certificates'
    | '/student/clubs'
    | '/student/compete'
    | '/student/lab'
    | '/student/leaderboard'
    | '/student/portfolio'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/analytics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/reviews'
    | '/admin/'
    | '/school/'
    | '/student/'
    | '/teacher/'
    | '/student/build/$projectId'
    | '/student/learn/$pathId'
    | '/teacher/classes/$classId'
    | '/teacher/students/$studentId'
    | '/student/build/'
    | '/student/learn/'
    | '/teacher/classes/'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/sync-role'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/competitions'
    | '/admin/curriculum'
    | '/admin/gamification'
    | '/admin/moderation'
    | '/admin/questions'
    | '/admin/schools'
    | '/admin/users'
    | '/school/classes'
    | '/school/readiness'
    | '/school/reports'
    | '/school/students'
    | '/school/teachers'
    | '/student/certificates'
    | '/student/clubs'
    | '/student/compete'
    | '/student/lab'
    | '/student/leaderboard'
    | '/student/portfolio'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/analytics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/reviews'
    | '/admin'
    | '/school'
    | '/student'
    | '/teacher'
    | '/student/build/$projectId'
    | '/student/learn/$pathId'
    | '/teacher/classes/$classId'
    | '/teacher/students/$studentId'
    | '/student/build'
    | '/student/learn'
    | '/teacher/classes'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/school'
    | '/student'
    | '/sync-role'
    | '/teacher'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/competitions'
    | '/admin/curriculum'
    | '/admin/gamification'
    | '/admin/moderation'
    | '/admin/questions'
    | '/admin/schools'
    | '/admin/users'
    | '/school/classes'
    | '/school/readiness'
    | '/school/reports'
    | '/school/students'
    | '/school/teachers'
    | '/student/certificates'
    | '/student/clubs'
    | '/student/compete'
    | '/student/lab'
    | '/student/leaderboard'
    | '/student/portfolio'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/analytics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/reviews'
    | '/admin/'
    | '/school/'
    | '/student/'
    | '/teacher/'
    | '/student/build/$projectId'
    | '/student/learn/$pathId'
    | '/teacher/classes/$classId'
    | '/teacher/students/$studentId'
    | '/student/build/'
    | '/student/learn/'
    | '/teacher/classes/'
    | '/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SchoolRoute: typeof SchoolRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SyncRoleRoute: typeof SyncRoleRoute
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-role': {
      id: '/sync-role'
      path: '/sync-role'
      fullPath: '/sync-role'
      preLoaderRoute: typeof SyncRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gamification': {
      id: '/admin/gamification'
      path: '/gamification'
      fullPath: '/admin/gamification'
      preLoaderRoute: typeof AdminGamificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/school/': {
      id: '/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/classes': {
      id: '/school/classes'
      path: '/classes'
      fullPath: '/school/classes'
      preLoaderRoute: typeof SchoolClassesRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/readiness': {
      id: '/school/readiness'
      path: '/readiness'
      fullPath: '/school/readiness'
      preLoaderRoute: typeof SchoolReadinessRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/reports': {
      id: '/school/reports'
      path: '/reports'
      fullPath: '/school/reports'
      preLoaderRoute: typeof SchoolReportsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/students': {
      id: '/school/students'
      path: '/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof SchoolStudentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/teachers': {
      id: '/school/teachers'
      path: '/teachers'
      fullPath: '/school/teachers'
      preLoaderRoute: typeof SchoolTeachersRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/clubs': {
      id: '/student/clubs'
      path: '/clubs'
      fullPath: '/student/clubs'
      preLoaderRoute: typeof StudentClubsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/compete': {
      id: '/student/compete'
      path: '/compete'
      fullPath: '/student/compete'
      preLoaderRoute: typeof StudentCompeteRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lab': {
      id: '/student/lab'
      path: '/lab'
      fullPath: '/student/lab'
      preLoaderRoute: typeof StudentLabRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/portfolio': {
      id: '/student/portfolio'
      path: '/portfolio'
      fullPath: '/student/portfolio'
      preLoaderRoute: typeof StudentPortfolioRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reviews': {
      id: '/teacher/reviews'
      path: '/reviews'
      fullPath: '/teacher/reviews'
      preLoaderRoute: typeof TeacherReviewsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/build/': {
      id: '/student/build/'
      path: '/build'
      fullPath: '/student/build/'
      preLoaderRoute: typeof StudentBuildIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/build/$projectId': {
      id: '/student/build/$projectId'
      path: '/build/$projectId'
      fullPath: '/student/build/$projectId'
      preLoaderRoute: typeof StudentBuildProjectIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn/': {
      id: '/student/learn/'
      path: '/learn'
      fullPath: '/student/learn/'
      preLoaderRoute: typeof StudentLearnIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn/$pathId': {
      id: '/student/learn/$pathId'
      path: '/learn/$pathId'
      fullPath: '/student/learn/$pathId'
      preLoaderRoute: typeof StudentLearnPathIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students/': {
      id: '/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof TeacherStudentsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  AdminGamificationRoute: typeof AdminGamificationRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  AdminGamificationRoute: AdminGamificationRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SchoolRouteChildren {
  SchoolClassesRoute: typeof SchoolClassesRoute
  SchoolReadinessRoute: typeof SchoolReadinessRoute
  SchoolReportsRoute: typeof SchoolReportsRoute
  SchoolStudentsRoute: typeof SchoolStudentsRoute
  SchoolTeachersRoute: typeof SchoolTeachersRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolClassesRoute: SchoolClassesRoute,
  SchoolReadinessRoute: SchoolReadinessRoute,
  SchoolReportsRoute: SchoolReportsRoute,
  SchoolStudentsRoute: SchoolStudentsRoute,
  SchoolTeachersRoute: SchoolTeachersRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentClubsRoute: typeof StudentClubsRoute
  StudentCompeteRoute: typeof StudentCompeteRoute
  StudentLabRoute: typeof StudentLabRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentPortfolioRoute: typeof StudentPortfolioRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentBuildProjectIdRoute: typeof StudentBuildProjectIdRoute
  StudentLearnPathIdRoute: typeof StudentLearnPathIdRoute
  StudentBuildIndexRoute: typeof StudentBuildIndexRoute
  StudentLearnIndexRoute: typeof StudentLearnIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentClubsRoute: StudentClubsRoute,
  StudentCompeteRoute: StudentCompeteRoute,
  StudentLabRoute: StudentLabRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentPortfolioRoute: StudentPortfolioRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentBuildProjectIdRoute: StudentBuildProjectIdRoute,
  StudentLearnPathIdRoute: StudentLearnPathIdRoute,
  StudentBuildIndexRoute: StudentBuildIndexRoute,
  StudentLearnIndexRoute: StudentLearnIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherReviewsRoute: typeof TeacherReviewsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherStudentsIndexRoute: typeof TeacherStudentsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherReviewsRoute: TeacherReviewsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherStudentsIndexRoute: TeacherStudentsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SchoolRoute: SchoolRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SyncRoleRoute: SyncRoleRoute,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
